telegram:
  bot:
    name: Lisa_IdealBot
    token: 6170968276:AAEvt_Sktp1H2-xIpDEEV2DIjy5MqYO1WsU
server:
  port: 8081

logging:
  level:
    root: warn
    ru: debug

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # localhost
    url: jdbc:postgresql://localhost:5432/superheroes-bd
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: validate
    defer-datasource-initialization: false
    open-in-view: false
  mandatory-file-encoding: UTF-8